apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: braianmg/comments:latest
--- # Separator to create multiple objects within the same file
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  # By default, Kubernetes creates a service of type ClusterIP, in this case it was not necessary to indicate the type
  # type: ClusterIP 
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
