apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: braianmg/moderation:latest
--- # Separator to create multiple objects within the same file
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  # By default, Kubernetes creates a service of type ClusterIP, in this case it was not necessary to indicate the type
  # type: ClusterIP 
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
